# Generated by Django 5.2.3 on 2025-06-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='factory_yaer',
            new_name='factory_year',
        ),
    ]
