# Generated by Django 5.2.4 on 2025-07-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinvertory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarInvertory',
            new_name='CarInventory',
        ),
    ]
